apiVersion: "v1"
kind: "Service"
metadata:
  name: wordpress
  namespace: exercise-02
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - nodePort: 32288
    protocol: TCP
    port: 80
    targetPort: http
